sudo: false

language: python

_helpers:
- &osx_python_base
  stage: &stage_test_osx_name test under OS X (last chance to fail before deploy available)
  os: osx
  language: generic


jobs:
  include:
  - <<: *osx_python_base
    python: 3.4

stages:
- name: *stage_test_osx_name
  if: type IN (api, cron) OR tag IS present

